services:
  backend:
    build:
      context: ./backend
      # Keep the CPU default
      dockerfile: ${DOCKERFILE:-Dockerfile.cpu} 
    container_name: visiondrive_backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/visiondrive
    depends_on:
      - mongo
    # Remove volume mount if models are static and copied in the Dockerfile
    # volumes:
    #   - ./backend/models:/app/models 
    
    # CRITICAL FIX: Remove GPU-related configuration for a CPU-default build
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
    # runtime: ${RUNTIME:-runc}
    
    # Keep the default runtime (runc) implicitly by removing the 'runtime' field
    networks:
      - visiondrive_net

  analytics:
    build: ./analytics
    container_name: visiondrive_analytics
    ports:
      - "8501:8501"
    environment:
      - MONGO_URI=mongodb://mongo:27017/visiondrive
    depends_on:
      - mongo
    networks:
      - visiondrive_net

  mongo:
    # BEST PRACTICE: Pin the MongoDB version
    image: mongo:7 # Example of pinning to a major version
    container_name: visiondrive_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - visiondrive_net

volumes:
  mongo_data:

networks:
  visiondrive_net:
    driver: bridge